---
deploy:
  master: 'echo ''I will speak on: hf deploy master'' '
  develop: 'echo ''I will speak on: hf deploy develop'' '
before_deploy_commit: 'echo ''Before committing with deploy'' '
locale: en
skip_colorize: false

task_branch_namespace: hotfix
source_branch: master
